/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.

The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.

```json http
{
  "method": "GET",
  "url": "https://api.spacetraders.io/v2",
}
```

Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.

We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.



 * OpenAPI spec version: 2.3.0
 */

export type ShipConditionEventSymbol =
  (typeof ShipConditionEventSymbol)[keyof typeof ShipConditionEventSymbol];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ShipConditionEventSymbol = {
  REACTOR_OVERLOAD: 'REACTOR_OVERLOAD',
  ENERGY_SPIKE_FROM_MINERAL: 'ENERGY_SPIKE_FROM_MINERAL',
  SOLAR_FLARE_INTERFERENCE: 'SOLAR_FLARE_INTERFERENCE',
  COOLANT_LEAK: 'COOLANT_LEAK',
  POWER_DISTRIBUTION_FLUCTUATION: 'POWER_DISTRIBUTION_FLUCTUATION',
  MAGNETIC_FIELD_DISRUPTION: 'MAGNETIC_FIELD_DISRUPTION',
  HULL_MICROMETEORITE_STRIKES: 'HULL_MICROMETEORITE_STRIKES',
  STRUCTURAL_STRESS_FRACTURES: 'STRUCTURAL_STRESS_FRACTURES',
  CORROSIVE_MINERAL_CONTAMINATION: 'CORROSIVE_MINERAL_CONTAMINATION',
  THERMAL_EXPANSION_MISMATCH: 'THERMAL_EXPANSION_MISMATCH',
  VIBRATION_DAMAGE_FROM_DRILLING: 'VIBRATION_DAMAGE_FROM_DRILLING',
  ELECTROMAGNETIC_FIELD_INTERFERENCE: 'ELECTROMAGNETIC_FIELD_INTERFERENCE',
  IMPACT_WITH_EXTRACTED_DEBRIS: 'IMPACT_WITH_EXTRACTED_DEBRIS',
  FUEL_EFFICIENCY_DEGRADATION: 'FUEL_EFFICIENCY_DEGRADATION',
  COOLANT_SYSTEM_AGEING: 'COOLANT_SYSTEM_AGEING',
  DUST_MICROABRASIONS: 'DUST_MICROABRASIONS',
  THRUSTER_NOZZLE_WEAR: 'THRUSTER_NOZZLE_WEAR',
  EXHAUST_PORT_CLOGGING: 'EXHAUST_PORT_CLOGGING',
  BEARING_LUBRICATION_FADE: 'BEARING_LUBRICATION_FADE',
  SENSOR_CALIBRATION_DRIFT: 'SENSOR_CALIBRATION_DRIFT',
  HULL_MICROMETEORITE_DAMAGE: 'HULL_MICROMETEORITE_DAMAGE',
  SPACE_DEBRIS_COLLISION: 'SPACE_DEBRIS_COLLISION',
  THERMAL_STRESS: 'THERMAL_STRESS',
  VIBRATION_OVERLOAD: 'VIBRATION_OVERLOAD',
  PRESSURE_DIFFERENTIAL_STRESS: 'PRESSURE_DIFFERENTIAL_STRESS',
  ELECTROMAGNETIC_SURGE_EFFECTS: 'ELECTROMAGNETIC_SURGE_EFFECTS',
  ATMOSPHERIC_ENTRY_HEAT: 'ATMOSPHERIC_ENTRY_HEAT',
} as const;
