/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.

The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.

```json http
{
  "method": "GET",
  "url": "https://api.spacetraders.io/v2",
}
```

Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.

We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.



 * OpenAPI spec version: 2.3.0
 */
import type { ShipComponentCondition } from '../models-ShipComponentCondition/shipComponentCondition';
import type { ShipComponentIntegrity } from '../models-ShipComponentIntegrity/shipComponentIntegrity';
import type { ShipComponentQuality } from '../models-ShipComponentQuality/shipComponentQuality';
import type { ShipRequirements } from '../models-ShipRequirements/shipRequirements';
import type { ShipFrameSymbol } from './shipFrameSymbol';

/**
 * The frame of the ship. The frame determines the number of modules and mounting points of the ship, as well as base fuel capacity. As the condition of the frame takes more wear, the ship will become more sluggish and less maneuverable.
 */
export interface ShipFrame {
  condition: ShipComponentCondition;
  /** Description of the frame. */
  description: string;
  /**
   * The maximum amount of fuel that can be stored in this ship. When refueling, the ship will be refueled to this amount.
   * @minimum 0
   */
  fuelCapacity: number;
  integrity: ShipComponentIntegrity;
  /**
   * The amount of slots that can be dedicated to modules installed in the ship. Each installed module take up a number of slots, and once there are no more slots, no new modules can be installed.
   * @minimum 0
   */
  moduleSlots: number;
  /**
   * The amount of slots that can be dedicated to mounts installed in the ship. Each installed mount takes up a number of points, and once there are no more points remaining, no new mounts can be installed.
   * @minimum 0
   */
  mountingPoints: number;
  /** Name of the frame. */
  name: string;
  quality: ShipComponentQuality;
  requirements: ShipRequirements;
  /** Symbol of the frame. */
  symbol: ShipFrameSymbol;
}
