/**
 * Generated by orval v8.0.0-rc.1 🍺
 * Do not edit manually.
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.

The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.

```json http
{
  "method": "GET",
  "url": "https://api.spacetraders.io/v2",
}
```

Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.

We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.



 * OpenAPI spec version: 2.3.0
 */

/**
 * Symbol of the frame.
 */
export type ShipFrameSymbol =
  (typeof ShipFrameSymbol)[keyof typeof ShipFrameSymbol];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ShipFrameSymbol = {
  FRAME_BULK_FREIGHTER: 'FRAME_BULK_FREIGHTER',
  FRAME_CARRIER: 'FRAME_CARRIER',
  FRAME_CRUISER: 'FRAME_CRUISER',
  FRAME_DESTROYER: 'FRAME_DESTROYER',
  FRAME_DRONE: 'FRAME_DRONE',
  FRAME_EXPLORER: 'FRAME_EXPLORER',
  FRAME_FIGHTER: 'FRAME_FIGHTER',
  FRAME_FRIGATE: 'FRAME_FRIGATE',
  FRAME_HEAVY_FREIGHTER: 'FRAME_HEAVY_FREIGHTER',
  FRAME_INTERCEPTOR: 'FRAME_INTERCEPTOR',
  FRAME_LIGHT_FREIGHTER: 'FRAME_LIGHT_FREIGHTER',
  FRAME_MINER: 'FRAME_MINER',
  FRAME_PROBE: 'FRAME_PROBE',
  FRAME_RACER: 'FRAME_RACER',
  FRAME_SHUTTLE: 'FRAME_SHUTTLE',
  FRAME_TRANSPORT: 'FRAME_TRANSPORT',
} as const;
