/**
 * Generated by orval v8.0.0-rc.1 🍺
 * Do not edit manually.
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.

The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.

```json http
{
  "method": "GET",
  "url": "https://api.spacetraders.io/v2",
}
```

Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.

We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.



 * OpenAPI spec version: 2.3.0
 */
import type { RequestHandlerOptions } from 'msw';

import { faker } from '@faker-js/faker';
import { http, HttpResponse } from 'msw';

import type { GetSupplyChain200 } from '../getSupplyChain200';

export const getGetSupplyChainResponseMock = (
  overrideResponse: Partial<GetSupplyChain200> = {},
): GetSupplyChain200 => ({
  data: {
    exportToImportMap: {
      [faker.string.alphanumeric(5)]: Array.from(
        { length: faker.number.int({ max: 10, min: 1 }) },
        (_, i) => i + 1,
      ).map(() => faker.string.alpha({ length: { max: 20, min: 10 } })),
    },
  },
  ...overrideResponse,
});

export const getGetSupplyChainResponseMock200 = (
  overrideResponse: Partial<GetSupplyChain200> = {},
): GetSupplyChain200 => ({
  data: {
    exportToImportMap: {
      [faker.string.alphanumeric(5)]: Array.from(
        { length: faker.number.int({ max: 10, min: 1 }) },
        (_, i) => i + 1,
      ).map(() => faker.string.alpha({ length: { max: 20, min: 10 } })),
    },
  },
  ...overrideResponse,
});

export const getGetSupplyChainMockHandler = (
  overrideResponse?:
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => GetSupplyChain200 | Promise<GetSupplyChain200>)
    | GetSupplyChain200,
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/market/supply-chain',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetSupplyChainResponseMock(),
        ),
        { headers: { 'Content-Type': 'application/json' }, status: 200 },
      );
    },
    options,
  );
};

export const getGetSupplyChainMockHandler200 = (
  overrideResponse?:
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => GetSupplyChain200 | Promise<GetSupplyChain200>)
    | GetSupplyChain200,
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/market/supply-chain',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetSupplyChainResponseMock200(),
        ),
        { headers: { 'Content-Type': 'application/json' }, status: 200 },
      );
    },
    options,
  );
};
export const getDataMock = () => [getGetSupplyChainMockHandler()];
