/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.

The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.

```json http
{
  "method": "GET",
  "url": "https://api.spacetraders.io/v2",
}
```

Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.

We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.



 * OpenAPI spec version: 2.3.0
 */
import type { ContractTerms } from "../models-ContractTerms/contractTerms";
import type { ContractType } from "./contractType";

/**
 * Contract details.
 */
export interface Contract {
  /** Whether the contract has been accepted by the agent */
  accepted: boolean;
  /** The time at which the contract is no longer available to be accepted */
  deadlineToAccept?: string;
  /**
   * Deprecated in favor of deadlineToAccept
   * @deprecated
   */
  expiration: string;
  /**
   * The symbol of the faction that this contract is for.
   * @minLength 1
   */
  factionSymbol: string;
  /** Whether the contract has been fulfilled */
  fulfilled: boolean;
  /**
   * ID of the contract.
   * @minLength 1
   */
  id: string;
  terms: ContractTerms;
  /** Type of contract. */
  type: ContractType;
}
