/**
 * Generated by orval v8.0.0-rc.1 🍺
 * Do not edit manually.
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.

The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.

```json http
{
  "method": "GET",
  "url": "https://api.spacetraders.io/v2",
}
```

Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.

We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.



 * OpenAPI spec version: 2.3.0
 */
import type { WaypointSymbol } from '../models-WaypointSymbol/waypointSymbol';

/**
 * Results of a transaction with a shipyard.
 */
export interface ShipyardTransaction {
  /** The symbol of the agent that made the transaction. */
  agentSymbol: string;
  /**
   * The price of the transaction.
   * @minimum 0
   */
  price: number;
  /**
   * The symbol of the ship type (e.g. SHIP_MINING_DRONE) that was the subject of the transaction. Contrary to what the name implies, this is NOT the symbol of the ship that was purchased.
   * @deprecated
   */
  shipSymbol: string;
  /** The symbol of the ship type (e.g. SHIP_MINING_DRONE) that was the subject of the transaction. */
  shipType: string;
  /** The timestamp of the transaction. */
  timestamp: string;
  waypointSymbol: WaypointSymbol;
}
