/**
 * Generated by orval v8.0.0-rc.1 🍺
 * Do not edit manually.
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.

The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.

```json http
{
  "method": "GET",
  "url": "https://api.spacetraders.io/v2",
}
```

Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.

We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.



 * OpenAPI spec version: 2.3.0
 */

/**
 * The unique identifier of the trait.
 */
export type FactionTraitSymbol =
  (typeof FactionTraitSymbol)[keyof typeof FactionTraitSymbol];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FactionTraitSymbol = {
  BUREAUCRATIC: 'BUREAUCRATIC',
  SECRETIVE: 'SECRETIVE',
  CAPITALISTIC: 'CAPITALISTIC',
  INDUSTRIOUS: 'INDUSTRIOUS',
  PEACEFUL: 'PEACEFUL',
  DISTRUSTFUL: 'DISTRUSTFUL',
  WELCOMING: 'WELCOMING',
  SMUGGLERS: 'SMUGGLERS',
  SCAVENGERS: 'SCAVENGERS',
  REBELLIOUS: 'REBELLIOUS',
  EXILES: 'EXILES',
  PIRATES: 'PIRATES',
  RAIDERS: 'RAIDERS',
  CLAN: 'CLAN',
  GUILD: 'GUILD',
  DOMINION: 'DOMINION',
  FRINGE: 'FRINGE',
  FORSAKEN: 'FORSAKEN',
  ISOLATED: 'ISOLATED',
  LOCALIZED: 'LOCALIZED',
  ESTABLISHED: 'ESTABLISHED',
  NOTABLE: 'NOTABLE',
  DOMINANT: 'DOMINANT',
  INESCAPABLE: 'INESCAPABLE',
  INNOVATIVE: 'INNOVATIVE',
  BOLD: 'BOLD',
  VISIONARY: 'VISIONARY',
  CURIOUS: 'CURIOUS',
  DARING: 'DARING',
  EXPLORATORY: 'EXPLORATORY',
  RESOURCEFUL: 'RESOURCEFUL',
  FLEXIBLE: 'FLEXIBLE',
  COOPERATIVE: 'COOPERATIVE',
  UNITED: 'UNITED',
  STRATEGIC: 'STRATEGIC',
  INTELLIGENT: 'INTELLIGENT',
  RESEARCH_FOCUSED: 'RESEARCH_FOCUSED',
  COLLABORATIVE: 'COLLABORATIVE',
  PROGRESSIVE: 'PROGRESSIVE',
  MILITARISTIC: 'MILITARISTIC',
  TECHNOLOGICALLY_ADVANCED: 'TECHNOLOGICALLY_ADVANCED',
  AGGRESSIVE: 'AGGRESSIVE',
  IMPERIALISTIC: 'IMPERIALISTIC',
  TREASURE_HUNTERS: 'TREASURE_HUNTERS',
  DEXTEROUS: 'DEXTEROUS',
  UNPREDICTABLE: 'UNPREDICTABLE',
  BRUTAL: 'BRUTAL',
  FLEETING: 'FLEETING',
  ADAPTABLE: 'ADAPTABLE',
  SELF_SUFFICIENT: 'SELF_SUFFICIENT',
  DEFENSIVE: 'DEFENSIVE',
  PROUD: 'PROUD',
  DIVERSE: 'DIVERSE',
  INDEPENDENT: 'INDEPENDENT',
  SELF_INTERESTED: 'SELF_INTERESTED',
  FRAGMENTED: 'FRAGMENTED',
  COMMERCIAL: 'COMMERCIAL',
  FREE_MARKETS: 'FREE_MARKETS',
  ENTREPRENEURIAL: 'ENTREPRENEURIAL',
} as const;
