/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.

The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.

```json http
{
  "method": "GET",
  "url": "https://api.spacetraders.io/v2",
}
```

Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.

We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.



 * OpenAPI spec version: 2.3.0
 */
import type { ShipComponentCondition } from "../models-ShipComponentCondition/shipComponentCondition";
import type { ShipComponentIntegrity } from "../models-ShipComponentIntegrity/shipComponentIntegrity";
import type { ShipComponentQuality } from "../models-ShipComponentQuality/shipComponentQuality";
import type { ShipRequirements } from "../models-ShipRequirements/shipRequirements";
import type { ShipEngineSymbol } from "./shipEngineSymbol";

/**
 * The engine determines how quickly a ship travels between waypoints.
 */
export interface ShipEngine {
  condition: ShipComponentCondition;
  /** The description of the engine. */
  description: string;
  integrity: ShipComponentIntegrity;
  /** The name of the engine. */
  name: string;
  quality: ShipComponentQuality;
  requirements: ShipRequirements;
  /**
   * The speed stat of this engine. The higher the speed, the faster a ship can travel from one point to another. Reduces the time of arrival when navigating the ship.
   * @minimum 1
   */
  speed: number;
  /** The symbol of the engine. */
  symbol: ShipEngineSymbol;
}
