/**
 * Generated by orval v8.0.0-rc.1 🍺
 * Do not edit manually.
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.

The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.

```json http
{
  "method": "GET",
  "url": "https://api.spacetraders.io/v2",
}
```

Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.

We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.



 * OpenAPI spec version: 2.3.0
 */
import type { ShipRequirements } from '../models-ShipRequirements/shipRequirements';
import type { ShipModuleSymbol } from './shipModuleSymbol';

/**
 * A module can be installed in a ship and provides a set of capabilities such as storage space or quarters for crew. Module installations are permanent.
 */
export interface ShipModule {
  /**
   * Modules that provide capacity, such as cargo hold or crew quarters will show this value to denote how much of a bonus the module grants.
   * @minimum 0
   */
  capacity?: number;
  /** Description of this module. */
  description: string;
  /** Name of this module. */
  name: string;
  /**
   * Modules that have a range will such as a sensor array show this value to denote how far can the module reach with its capabilities.
   * @minimum 0
   */
  range?: number;
  requirements: ShipRequirements;
  /** The symbol of the module. */
  symbol: ShipModuleSymbol;
}
