/**
 * Generated by orval v8.0.0-rc.1 🍺
 * Do not edit manually.
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.

The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.

```json http
{
  "method": "GET",
  "url": "https://api.spacetraders.io/v2",
}
```

Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.

We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.



 * OpenAPI spec version: 2.3.0
 */
import type { ActivityLevel } from '../models-ActivityLevel/activityLevel';
import type { SupplyLevel } from '../models-SupplyLevel/supplyLevel';
import type { TradeSymbol } from '../models-TradeSymbol/tradeSymbol';
import type { MarketTradeGoodType } from './marketTradeGoodType';

export interface MarketTradeGood {
  activity?: ActivityLevel;
  /**
   * The price at which this good can be purchased from the market.
   * @minimum 0
   */
  purchasePrice: number;
  /**
   * The price at which this good can be sold to the market.
   * @minimum 0
   */
  sellPrice: number;
  supply: SupplyLevel;
  symbol: TradeSymbol;
  /**
   * This is the maximum number of units that can be purchased or sold at this market in a single trade for this good. Trade volume also gives an indication of price volatility. A market with a low trade volume will have large price swings, while high trade volume will be more resilient to price changes.
   * @minimum 1
   */
  tradeVolume: number;
  /** The type of trade good (export, import, or exchange). */
  type: MarketTradeGoodType;
}
