/**
 * Generated by orval v8.0.0-rc.1 🍺
 * Do not edit manually.
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.

The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.

```json http
{
  "method": "GET",
  "url": "https://api.spacetraders.io/v2",
}
```

Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.

We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.



 * OpenAPI spec version: 2.3.0
 */
import type { ShipCargo } from '../models-ShipCargo/shipCargo';
import type { Cooldown } from '../models-Cooldown/cooldown';
import type { ShipCrew } from '../models-ShipCrew/shipCrew';
import type { ShipEngine } from '../models-ShipEngine/shipEngine';
import type { ShipFrame } from '../models-ShipFrame/shipFrame';
import type { ShipFuel } from '../models-ShipFuel/shipFuel';
import type { ShipModule } from '../models-ShipModule/shipModule';
import type { ShipMount } from '../models-ShipMount/shipMount';
import type { ShipNav } from '../models-ShipNav/shipNav';
import type { ShipReactor } from '../models-ShipReactor/shipReactor';
import type { ShipRegistration } from '../models-ShipRegistration/shipRegistration';

/**
 * Ship details.
 */
export interface Ship {
  cargo: ShipCargo;
  cooldown: Cooldown;
  crew: ShipCrew;
  engine: ShipEngine;
  frame: ShipFrame;
  fuel: ShipFuel;
  /** Modules installed in this ship. */
  modules: ShipModule[];
  /** Mounts installed in this ship. */
  mounts: ShipMount[];
  nav: ShipNav;
  reactor: ShipReactor;
  registration: ShipRegistration;
  /** The globally unique identifier of the ship in the following format: `[AGENT_SYMBOL]-[HEX_ID]` */
  symbol: string;
}
