/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.

The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.

```json http
{
  "method": "GET",
  "url": "https://api.spacetraders.io/v2",
}
```

Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.

We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.



 * OpenAPI spec version: 2.3.0
 */
import type { SystemFaction } from "../models-SystemFaction/systemFaction";
import type { SystemType } from "../models-SystemType/systemType";
import type { SystemWaypoint } from "../models-SystemWaypoint/systemWaypoint";

/**
 * System details.
 */
export interface System {
  /** The constellation that the system is part of. */
  constellation?: string;
  /** Factions that control this system. */
  factions: SystemFaction[];
  /** The name of the system. */
  name?: string;
  /**
   * The symbol of the sector.
   * @minLength 1
   */
  sectorSymbol: string;
  /**
   * The symbol of the system.
   * @minLength 1
   */
  symbol: string;
  type: SystemType;
  /** Waypoints in this system. */
  waypoints: SystemWaypoint[];
  /** Relative position of the system in the sector in the x axis. */
  x: number;
  /** Relative position of the system in the sector in the y axis. */
  y: number;
}
