/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.

The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.

```json http
{
  "method": "GET",
  "url": "https://api.spacetraders.io/v2",
}
```

Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.

We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.



 * OpenAPI spec version: 2.3.0
 */
import type { FactionSymbol } from '../models-FactionSymbol/factionSymbol';
import type { FactionTrait } from '../models-FactionTrait/factionTrait';

/**
 * Faction details.
 */
export interface Faction {
  /**
   * Description of the faction.
   * @minLength 1
   */
  description: string;
  /**
   * The waypoint in which the faction's HQ is located in.
   * @minLength 1
   */
  headquarters?: string;
  /** Whether or not the faction is currently recruiting new agents. */
  isRecruiting: boolean;
  /**
   * Name of the faction.
   * @minLength 1
   */
  name: string;
  symbol: FactionSymbol;
  /** List of traits that define this faction. */
  traits: FactionTrait[];
}
