/**
 * Generated by orval v8.0.0-rc.1 🍺
 * Do not edit manually.
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.

The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.

```json http
{
  "method": "GET",
  "url": "https://api.spacetraders.io/v2",
}
```

Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.

We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.



 * OpenAPI spec version: 2.3.0
 */
import type { ShipNav } from '../models-ShipNav/shipNav';
import type { ShipRegistration } from '../models-ShipRegistration/shipRegistration';
import type { ScannedShipEngine } from './scannedShipEngine';
import type { ScannedShipFrame } from './scannedShipFrame';
import type { ScannedShipMountsItem } from './scannedShipMountsItem';
import type { ScannedShipReactor } from './scannedShipReactor';

/**
 * The ship that was scanned. Details include information about the ship that could be detected by the scanner.
 */
export interface ScannedShip {
  /** The engine of the ship. */
  engine: ScannedShipEngine;
  /** The frame of the ship. */
  frame?: ScannedShipFrame;
  /** List of mounts installed in the ship. */
  mounts?: ScannedShipMountsItem[];
  nav: ShipNav;
  /** The reactor of the ship. */
  reactor?: ScannedShipReactor;
  registration: ShipRegistration;
  /** The globally unique identifier of the ship. */
  symbol: string;
}
