/**
 * Generated by orval v8.0.0-rc.1 🍺
 * Do not edit manually.
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.

The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.

```json http
{
  "method": "GET",
  "url": "https://api.spacetraders.io/v2",
}
```

Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.

We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.



 * OpenAPI spec version: 2.3.0
 */
import type { Chart } from '../models-Chart/chart';
import type { WaypointFaction } from '../models-WaypointFaction/waypointFaction';
import type { WaypointOrbital } from '../models-WaypointOrbital/waypointOrbital';
import type { WaypointSymbol } from '../models-WaypointSymbol/waypointSymbol';
import type { SystemSymbol } from '../models-SystemSymbol/systemSymbol';
import type { WaypointTrait } from '../models-WaypointTrait/waypointTrait';
import type { WaypointType } from '../models-WaypointType/waypointType';

/**
 * A waypoint that was scanned by a ship.
 */
export interface ScannedWaypoint {
  chart?: Chart;
  faction?: WaypointFaction;
  /** List of waypoints that orbit this waypoint. */
  orbitals: WaypointOrbital[];
  symbol: WaypointSymbol;
  systemSymbol: SystemSymbol;
  /** The traits of the waypoint. */
  traits: WaypointTrait[];
  type: WaypointType;
  /** Position in the universe in the x axis. */
  x: number;
  /** Position in the universe in the y axis. */
  y: number;
}
