/**
 * Generated by orval v8.0.0-rc.1 🍺
 * Do not edit manually.
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.

The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.

```json http
{
  "method": "GET",
  "url": "https://api.spacetraders.io/v2",
}
```

Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.

We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.



 * OpenAPI spec version: 2.3.0
 */
import type { GetStatus200AnnouncementsItem } from './getStatus200AnnouncementsItem';
import type { GetStatus200Leaderboards } from './getStatus200Leaderboards';
import type { GetStatus200LinksItem } from './getStatus200LinksItem';
import type { GetStatus200ServerResets } from './getStatus200ServerResets';
import type { GetStatus200Stats } from './getStatus200Stats';

export type GetStatus200 = {
  announcements: GetStatus200AnnouncementsItem[];
  description: string;
  leaderboards: GetStatus200Leaderboards;
  links: GetStatus200LinksItem[];
  /** The date when the game server was last reset. */
  resetDate: string;
  serverResets: GetStatus200ServerResets;
  stats: GetStatus200Stats;
  /** The current status of the game server. */
  status: string;
  /** The current version of the API. */
  version: string;
};
